### ISSUE TITLE
What is the license of this software?

### ISSUE THREAD

**Issue by bkuhn** [mmonka/mail2pdf#11]
This script looks interesting, and I have the need to convert mbox files to PDF, but I don't see a copyright license on this repository.

Have you considered releasing it under an Open Source and Free Software license?

I'd be happy to help you pick one if you have questions.

**Comment by mmonka** [comment]
Hi,

i added the License GPLv2 to the Readme.
Feel free to contribute / change / add code.

**Comment by mmonka** [comment]
Actually my main focus is to fetch emails from an imap account, but you can 
switch between imap or mbox by using the "--type" option. The result should be
the same.
